Indigo/Controllers/JournalsController.cs
using Indigo.Constants;
using Indigo.Data;
using Indigo.Models;
using Indigo.Repositories.Interfaces;
using Indigo.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Indigo.Controllers
{
    [Authorize]
    public class JournalsController : Controller
    {
        private readonly IJournalRepository _repository;
        private readonly UserManager<IdentityUser> _userManager;

        public JournalsController(IJournalRepository repository, 
            UserManager<IdentityUser> userManager)
        {
            _repository = repository;
            _userManager = userManager;
        }

        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {
            if (User.IsInRole(Roles.Publisher))
            {
                var allJournals = await _repository.GetAllJournalsAsync();
                var userId = _userManager.GetUserId(User);
                var filteredJournals = allJournals.Where(j => j.UserId == userId);

                return View(filteredJournals);
            }

            var journals = await _repository.GetAllJournalsAsync();
            return View(journals);
        }

        [HttpGet]
        [Authorize(Roles = "Admin,Publisher")]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [Authorize(Roles = "Admin,Publisher")]
        public async Task<IActionResult> Create(JournalViewModel journalVm)
        {
            if (ModelState.IsValid)
            {
                byte[]? imageData = null;
                string? mimeType = null;

                if (journalVm.ImageFile != null && journalVm.ImageFile.Length > 0)
                {
                    using (var ms = new MemoryStream())
                    {
                        await journalVm.ImageFile.CopyToAsync(ms);
                        imageData = ms.ToArray();
                        mimeType = journalVm.ImageFile.ContentType;
                    }
                }

                var journal = new Journal
                {
                    Title = journalVm.Title,
                    Description = journalVm.Description,
                    ISSN_Online = journalVm.ISSN_Online,
                    ISSN_Print = journalVm.ISSN_Print,
                    License = journalVm.License,
                    ImageData = imageData,
                    ImageMimeType = mimeType,
                    UserId = _userManager.GetUserId(User),
                };

                await _repository.AddAsync(journal);
            }
            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        [Authorize(Roles = "Admin,Publisher")]
        public async Task<IActionResult> Edit(int id)
        {
            if (id == 0)
            {
                return NotFound();
            }

            Journal journal = await _repository.GetJournalByIdAsync(id);

            if (journal == null)
            {
                return NotFound();
            }

            var journalVm = new JournalViewModel
            {
                Title = journal.Title,
                Description = journal.Description,
                ISSN_Online = journal.ISSN_Online,
                ISSN_Print = journal.ISSN_Print,
                License = journal.License,
            };

            return View(journalVm);
        }

        [HttpPost]
        [Authorize(Roles = "Admin,Publisher")]
        public async Task<IActionResult> Edit(JournalViewModel journalVm, int id)
        {
            if (journalVm != null && journalVm.Title.Length < 3)
            {
                ModelState.AddModelError("Title", "Заглавието е твърде кратко");
            }

            if (ModelState.IsValid)
            {
                var journal = await _repository.GetJournalByIdAsync(id);

                if (journal == null)
                {
                    return NotFound();
                }

                journal.Title = journalVm.Title;
                journal.Description = journalVm.Description;
                journal.ISSN_Online = journalVm.ISSN_Online;
                journal.ISSN_Print = journalVm.ISSN_Print;
                journal.License = journalVm.License;

                if (journalVm.ImageFile != null && journalVm.ImageFile.Length > 0)
                {
                    using (var ms = new MemoryStream())
                    {
                        await journalVm.ImageFile.CopyToAsync(ms);
                        journal.ImageData = ms.ToArray();
                        journal.ImageMimeType = journalVm.ImageFile.ContentType;
                    }
                }

                await _repository.UpdateAsync(journal);
                return RedirectToAction(nameof(Index));
            }
            return View(journalVm);
        }

        [HttpGet]
        [AllowAnonymous]
        public async Task<IActionResult> Journal(int journalId)
        {
            if (journalId == 0)
            {
                return NotFound();
            }

            Journal journal = await _repository.GetJournalByIdAsync(journalId);

            if (journal == null)
            {
                return NotFound();
            }

            return View(journal);
        }

        [HttpDelete]
        [Authorize(Roles = "Admin,Publisher")]
        public async Task<IActionResult> Delete(int id)
        {
            var journal = await _repository.GetJournalByIdAsync(id);

            if (journal == null)
            {
                return NotFound();
            }

            var userId = _userManager.GetUserId(User);

            if (User.IsInRole(Roles.Admin) == false && journal.UserId != userId)
            {
                return Forbid();
            }

            await _repository.DeleteAsync(id);
            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        [AllowAnonymous]
        public async Task<IActionResult> Search(string title)
        {
            var allJournals = await _repository.GetAllJournalsAsync();

            if (string.IsNullOrWhiteSpace(title))
            {
                return View("Index", allJournals);
            }

            var filteredJournals = allJournals
                .Where(j => j.Title.Contains(title, StringComparison.OrdinalIgnoreCase));

            return View("Index", filteredJournals);
        }

        [HttpGet]
        [AllowAnonymous]
        public async Task<IActionResult> GetImage(int id)
        {
            var journal = await _repository.GetJournalByIdAsync(id);

            if (journal == null || journal.ImageData == null || journal.ImageMimeType == null)
            {
                return NotFound();
            }

            return File(journal.ImageData, journal.ImageMimeType);
        }
    }
}

Indigo/Controllers/UsersController.cs
using Indigo.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion.Internal;
using NuGet.Packaging;

namespace Indigo.Controllers
{
    [Authorize(Roles = "Admin")]
    public class UsersController : Controller
    {
        private readonly UserManager<IdentityUser> _userManager;
        public UsersController(UserManager<IdentityUser> userManager)
        {
            _userManager = userManager;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var allUsers = _userManager.Users.ToList();
            var userViewModels = new List<UserViewModel>();

            foreach (var user in allUsers)
            {
                var roles = await _userManager.GetRolesAsync(user);
                var role = roles.FirstOrDefault();

                if (role == "Publisher" || role == "Author" || role == "Reviewer")
                {
                    userViewModels.Add
                    (
                        new UserViewModel
                        {
                            Id = user.Id,
                            Email = user.Email,
                            Role = role
                        }
                    );
                }
            }

            return View(userViewModels);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(string id)
        {
            var user = await _userManager.FindByIdAsync(id);

            if (user == null)
            {
                return NotFound();
            }

            await _userManager.DeleteAsync(user);
            return RedirectToAction(nameof(Index));
        }
    }
}

Indigo/Views/Shared/_Layout.cshtml
@using Indigo.Constants;

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Индиго</title>
    <script type="importmap"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/Journals/Edit.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/Journals/Create.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/Journals/Index.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Indigo.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/_Layout.cshtml.css" asp-append-version="true" />
</head>
<body>
    <header class="headerContainer">
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <img src="/Images/Indigo.png" class="img-fluid imgLogo"/>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between text-end">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light fs-4" asp-area="" asp-controller="Home" asp-action="Index">Начало</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light fs-4" asp-area="" asp-controller="Journals" asp-action="Index">Списания</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light fs-4" asp-area="" asp-controller="Documentations" asp-action="Index">Документация</a>
                        </li>
                        @if(User.IsInRole(Roles.Publisher) || User.IsInRole(Roles.Admin))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-light fs-4" asp-area="" asp-controller="Journals" asp-action="Create">Създаване</a>
                            </li>
                        }
                        @if (User.IsInRole(Roles.Admin))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-light fs-4" asp-area="" asp-controller="Users" asp-action="Index">Потребители</a>
                            </li>
                        }
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item identityBtn">
                                <a class="nav-link text-light fs-4 text-end" asp-area="Identity" asp-page="/Account/Logout">Изход</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item identityBtn">
                                <a class="nav-link text-light fs-4 text-end" asp-area="Identity" asp-page="/Account/Login">Вход</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-light fs-4 text-end" asp-area="Identity" asp-page="/Account/Register">Регистрация</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-light text-center">
        <div class="container">
            Създаден от: Мартин Маринов
            <svg xmlns="http://www.w3.org/2000/svg" width="21" height="25" fill="currentColor" class="bi bi-rocket-takeoff-fill" viewBox="0 0 16 16">
                <path d="M12.17 9.53c2.307-2.592 3.278-4.684 3.641-6.218.21-.887.214-1.58.16-2.065a3.6 3.6 0 0 0-.108-.563 2 2 0 0 0-.078-.23V.453c-.073-.164-.168-.234-.352-.295a2 2 0 0 0-.16-.045 4 4 0 0 0-.57-.093c-.49-.044-1.19-.03-2.08.188-1.536.374-3.618 1.343-6.161 3.604l-2.4.238h-.006a2.55 2.55 0 0 0-1.524.734L.15 7.17a.512.512 0 0 0 .433.868l1.896-.271c.28-.04.592.013.955.132.232.076.437.16.655.248l.203.083c.196.816.66 1.58 1.275 2.195.613.614 1.376 1.08 2.191 1.277l.082.202c.089.218.173.424.249.657.118.363.172.676.132.956l-.271 1.9a.512.512 0 0 0 .867.433l2.382-2.386c.41-.41.668-.949.732-1.526zm.11-3.699c-.797.8-1.93.961-2.528.362-.598-.6-.436-1.733.361-2.532.798-.799 1.93-.96 2.528-.361s.437 1.732-.36 2.531Z" />
                <path d="M5.205 10.787a7.6 7.6 0 0 0 1.804 1.352c-1.118 1.007-4.929 2.028-5.054 1.903-.126-.127.737-4.189 1.839-5.18.346.69.837 1.35 1.411 1.925" />
            </svg>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>